// JsFromRoutes CacheKey 67e5dd508584d3820923a11b5794376a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as categories } from './CategoriesApi'
export { default as products } from './ProductsApi'
export { default as users } from './UsersApi'
export { default as orders } from './OrdersApi'
