// JsFromRoutes CacheKey 5552fa353b6d59c099e48a87b5e27efa
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/products'),
  create: /* #__PURE__ */ definePathHelper('post', '/products'),
  new: /* #__PURE__ */ definePathHelper('get', '/products/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/products/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/products/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/products/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/products/:id'),
}
